### ISSUE TITLE
Unable to change course visibility to open

### ISSUE THREAD

**Issue by michaelha** [PoeticMediaLab/Lacuna#217]
I'm unable to make a course public by changing to course visibility.  Here's a screenshot. ![image](https://user-images.githubusercontent.com/213290/38376831-587159b6-38ae-11e8-8003-0345d3771b1e.png)

Steps to reproduce:

1. Create a new course (e.g. MATH123) and the course appears on the homepage under section "Not Enrolled"
2. Go to the Edit screen of the newly created course (e.g. https://annotate2.arts.ubc.ca/node/101/edit)
3. Change Course Visibility to "Closed: Not visible to students. I will edit it later to make it visible."
4. Hit "Save" button
5. Return to Edit screen again
6. Change Course Visibility to "Open: Students can find it and join. I will authenticate their access."
7. Navigate to the homepage (i.e. https://annotate2.arts.ubc.ca/)
8. Check courses under the title "Not Enrolled" and I cannot find the course "MATH123"

**Comment by dabush** [comment]
Hi Michael,
Is it the case that the course is still saved as "Closed" (and not "Open")
or is it simply the case that you can't see the course on the home screen?
If the latter, that's probably a caching issue.


Daniel

**Comment by michaelha** [comment]
@dabush It's the latter.  Any idea where to troubleshoot caching issue?  I'm running this site using Drupal 7.58 on a RHEL 7 VM with PHP 5.4.16.  There's no PHP and opcode caching.

**Comment by dabush** [comment]
In my experience this is usually the result of browser caching. Try opening the page in a new browser or an incognito window and see if you can see the course then. If not, it's possible that the View is being cached (although caching should be turned off on this view in theory) and you can flush the site caches to get it to show up.

**Comment by dabush** [comment]
As a general rule, I recommend not setting courses to "Closed" for this reason- there's really no security risk since students will have to be enrolled manually to get inside courses anyway. And once it's set to Closed you can run into caching issues

**Comment by michaelha** [comment]
I was able to reproduce the error using incognito mode in Chrome Version 65.0.3325.181 (Official Build) (64-bit).

The reason why this is set to "Closed" and then "Open" is for instructor to drafting material in "Closed" mode before releasing the course to public for student enrollment.

**Comment by dabush** [comment]
Okay, so it sounds like it's not a browser caching problem; and I just went
to the url above and only saw one course (Millenials in Love- I take it
that's not the course?). So the next thing to try is to flush the cache-
you can do this through drush or from the admin menu:
https://www.drupal.org/docs/7/administering-drupal-7-site/clearing-or-rebuilding-drupals-cache

**Comment by michaelha** [comment]
Thanks for the suggestion @dabush 

I followed the link and still no success after trying the following ways to clear the cache:
"Clearing the cache" - from admin UI
"Drush"
"Run update.php"
"A PHP file to clear caches and rebuild the routing tables"

**Comment by michaelha** [comment]
I'm still trying to resolve this issue.  Any help would be greatly appreciated.

**Comment by dabush** [comment]
Hi @michaelha : at this point you could try to resolve this caching issue (not sure what's causing it) or you could create a new course and set it to open. Have you added many  materials to the course that is not visible? If you haven't, it might be worth simply creating a new one and deleting the old one. The new one will definitely show up.

**Comment by mwidner** [comment]
An alternate option might be to delete that entire field for setting courses private / public. That's probably coming in the next release anyway just to streamline the process a little. There's probably 1-2 other things that change would touch, but if it's something you're interested in, we can document the steps or quickly update the latest version to include that change.

**Comment by michaelha** [comment]
Thanks for getting back @mwidner 

> An alternate option might be to delete that entire field for setting courses private / public
Is that something I can do from the admin side or are you thinking code level changes?

We already have some content populated from instructor and help of instructional designer so it'd be preferred that we don't have to redo much of the work.

When is the next release date? I'd be interested to get the latest update when it's available.

**Comment by dabush** [comment]
Hi Michael,
You can delete that field by (from the admin menu) going to Structure ->
Content types -> Course -> Manage fields -> and deleting the field "Course
Visibility." Then your Lacuna installation will no longer filter by whether
a course is open or closed and all of them should show up by default.


Daniel

**Comment by michaelha** [comment]
Thanks for the instruction. I tried the steps but don't see the "Manage fields" menu. 

![image](https://user-images.githubusercontent.com/213290/39481862-be491102-4d21-11e8-9252-e472099d55b1.png)

**Comment by dabush** [comment]
It sounds like you don't have the appropriate permission. Under people -> permission, the permissions for "Field" should look like this:
<img width="930" alt="screenshot 2018-05-11 11 51 38" src="https://user-images.githubusercontent.com/9117334/39941563-d055494a-5511-11e8-96de-93afdcd68c14.png">
It should just be a matter of giving yourself this permission
