### ISSUE TITLE
LacunaStories - How to add a new year to Lacunastories

### ISSUE THREAD

**Issue by pguerr061703** [PoeticMediaLab/Lacuna#226]
Hello. This may be a newbie question, but how do I add the course "year" to my Course...example 2018-2019,  2019-2020 ?  Can someone please tell me where in the menus (step by step) can I add the 'year'?  I cannot seem to find it.  (see attached)

Thank you kindly

<img width="1066" alt="lacunastories-screenshot" src="https://user-images.githubusercontent.com/12171475/44104923-213e27fe-9fbe-11e8-9ea7-7b43e2388823.png">

**Comment by dabush** [comment]
Hi,
You can add years to the list by going to Structure-> content types->
course-> manage fields-> year and editing that field. We’ve been meaning to
address this and will have a new version out with added years shortly
(thanks for the reminder!).


Daniel
