### ISSUE TITLE
Lacunastories  - Cannot update the 'year' field of the course

### ISSUE THREAD

**Issue by pguerr061703** [PoeticMediaLab/Lacuna#227]
Hello, when I am in Lacunastories and try to add a year to the course (i.e 2018-2019, 2019-2020), I cannot. It says there is a data in the database and won't allow the year field to be changed. How can I fix this?  I am running mysql. Not sure how this happened. (See attached)

![image](https://user-images.githubusercontent.com/12171475/44111650-08bf97d6-9fd1-11e8-8433-83395f41b718.png)

**Comment by fparviz** [comment]
Hello,

You can just ignore the message "there is data for this field in the database. the field settings can no longer be changed" and click _Save field settings_ at the bottom of the page. And then in the next page, do not add anything in the form fields and just click Save.

Once you go back to the main page, the year field will be present in the drop down.

Let us know if this works for you.

Regards,
Fyza

**Comment by pguerr061703** [comment]
This does work for me. But for some strange reason, it does NOT work for another colleague of mine who has "Site Administrator" access. 
I see all options under the Structure menu.
I see everything Structure-->Course Types->Course-->Delete, Access Control, Manage Fields, Manage Display
He see only Structure-->Course Types -->Course--> Delete and Access Control

We are BOTH SITE ADMINISTRATORS on this Lacunastories site
![image](https://user-images.githubusercontent.com/12171475/44118584-a2741830-9fe4-11e8-9a50-1a37a660dbe4.png)

![image](https://user-images.githubusercontent.com/12171475/44118625-c3932f56-9fe4-11e8-9d4e-cbd464c5dfe5.png)

**Comment by dabush** [comment]
You might need to rebuild permissions (under Reports -> Status report), or
make sure that Site Administrators have access to the "administer fields"
permission (Under People--> permissions). If one of you is logged in as the
first user that might explain why the permissions are slightly different.

Daniel

**Comment by mwidner** [comment]
Also, we've just pushed an update to the system that includes the next few years. We obviously need a more sustainable solution, but that should give you what you need for now.
