### ISSUE TITLE
Update rules module for PHP 7.2 compatibility

### ISSUE THREAD

**Issue by szeidler** [PoeticMediaLab/Lacuna#234]
We're using PHP 7.2 on our servers and we're getting fatal errors with the Rules modules under some circumstances.

The PHP 7.2 compatibility got fixed in the [7.x-2.11 rules release](https://www.drupal.org/project/rules/releases/7.x-2.11) in May. To make Lacuna 7.2 compatible, the module should be updated on its next iteration.

**Comment by dabush** [comment]
Thanks for pointing this out- there's a pull request in now with an updated rules module and this should be taken care of shortly. If you run into any more bugs let us know!
